FROM quay.io/fedora/fedora-bootc:latest
RUN dnf install -y niri --setopt=install_weak_deps=False
RUN dnf install -y niri
RUN dnf install -y noctalia
RUN dnf install -y fuzzel swaybg swaylock swayidle wlogout mako
RUN dnf install -y alacritty nautilus
