FROM scratch AS ctx

COPY --chmod=0755 ./test/build.sh /
COPY --chmod=0755 ./common/ /

FROM quay.io/fedora/fedora-silverblue:latest

#RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
#    --mount=type=tmpfs,dst=/var \
#    --mount=type=cache,dst=/var/cache \
#    --mount=type=cache,dst=/var/log \
#    --mount=type=cache,dst=/var/lib/dnf \
#    --mount=type=tmpfs,dst=/tmp \
#    --mount=type=tmpfs,dst=/run \
#    /ctx/build.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/run \
    /ctx/build.sh && /ctx/initramfs.sh

RUN bootc container lint
