FROM scratch AS ctx

COPY --chmod=0755 ./test/build.sh /
COPY --chmod=0755 ./common/ /

FROM quay.io/fedora/fedora-bootc:latest

RUN mkdir -p /usr/lib/bootupd/updates \
    && cp -r /usr/lib/efi/*/*/* /usr/lib/bootupd/updates

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/run \
    /ctx/build.sh && /ctx/initramfs.sh

RUN bootc container lint
