FROM scratch AS ctx

COPY --chmod=0755 ./test/build.sh /

FROM quay.io/fedora/fedora-silverblue:latest

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh

RUN bootc container lint
