FROM docker.io/cachyos/cachyos-v3:latest

RUN pacman -Syu --noconfirm \
 && pacman -S --noconfirm \
        cachyos-gaming-meta \
        cachyos-gaming-applications \
        steam \
        heroic-games-launcher \
        faugus-launcher \
        prismlauncher \
        umu-launcher \
        goverlay \
        protonup-qt \
        protonplus \
 && pacman -Scc --noconfirm
