name: Test Reusable Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
    - ".github/workflows/reusable-action.yml"
    - ".github/workflows/test-workflow.yaml"
jobs:
  test:
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-action.yml
    with:
      containerfile: test/Containerfile-reusable-workflow-test
      image-name: test-reusable-workflow
      tag: latest
      space: true
      rechunk: true
      push: true
      sign: true
