ARG SUBDIR=desktop

FROM scratch AS ctx

ARG SUBDIR
COPY --chmod=0755 ./${SUBDIR}/build.sh /
COPY ./${SUBDIR}/packages /packages/specific
COPY ./common/packages /packages/common

FROM quay.io/fedora/fedora-bootc:latest

COPY ./${SUBDIR}/system_files /

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh

RUN bootc container lint
